--------------------------------------------------------
--  File created - Tuesday-February-12-2019
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HOMEOWNER
--------------------------------------------------------

  CREATE TABLE "HOMEINSURANCE"."HOMEOWNER"
   (	"USERID" NUMBER(10,0), 
	"FNAME" VARCHAR2(30 BYTE),
	"LNAME" VARCHAR2(30 BYTE),
	"DOB" VARCHAR2(10 BYTE),
	"RETIRED" NUMBER(1,0),
	"SSN" VARCHAR2(9 BYTE),
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "HOMEINSURANCE"."LOCATION"
   (	"LOCATIONID" NUMBER(10,0),
	"USERID" NUMBER(10,0),
	"RESTYPE" VARCHAR2(20 BYTE),
	"ADDR1" VARCHAR2(50 BYTE),
	"ADDR2" VARCHAR2(100 BYTE),
	"CITY" VARCHAR2(15 BYTE),
	"STATENAME" VARCHAR2(15 BYTE),
	"ZIP" NUMBER(10,0),
	"RESUSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POLICY
--------------------------------------------------------

  CREATE TABLE "HOMEINSURANCE"."POLICY"
   (	"POLICYID" NUMBER(10,0),
	"USERID" NUMBER(10,0),
	"QUOTEID" NUMBER(10,0),
	"EFFECTIVEDATE" VARCHAR2(20 BYTE),
	"ENDDATE" VARCHAR2(20 BYTE),
	"TERM" NUMBER(3,0),
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROPERTY
--------------------------------------------------------

  CREATE TABLE "HOMEINSURANCE"."PROPERTY"
   (	"LOCATIONID" NUMBER(10,0),
	"MKTVAL" NUMBER(10,0),
	"YR" NUMBER(4,0),
	"SQFT" NUMBER(10,0),
	"DWELLING" VARCHAR2(20 BYTE),
	"ROOFMTL" VARCHAR2(20 BYTE),
	"GARAGE" VARCHAR2(20 BYTE),
	"BATHS" NUMBER(2,0),
	"HALFBATHS" NUMBER(2,0),
	"POOL" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table QUOTE
--------------------------------------------------------

  CREATE TABLE "HOMEINSURANCE"."QUOTE"
   (	"QUOTEID" NUMBER(10,0),
	"LOCATIONID" NUMBER(10,0),
	"MNTHLYPREMIUM" NUMBER(10,2),
	"DWELLINGCOVERAGE" NUMBER(10,2),
	"DETACHEDSTRUCTURE" NUMBER(10,2),
	"PERSONALPROPERTY" NUMBER(10,2),
	"ADDLLIVINGEXPENSE" NUMBER(10,2),
	"MEDICALEXPENSE" NUMBER(10,2),
	"DEDUCTIBLE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERLIST
--------------------------------------------------------

  CREATE TABLE "HOMEINSURANCE"."USERLIST"
   (	"USERID" NUMBER(10,0),
	"USERNAME" VARCHAR2(20 BYTE),
	"USERPASS" VARCHAR2(20 BYTE),
	"ROLE" VARCHAR2(20 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HOMEINSURANCE.HOMEOWNER
SET DEFINE OFF;
REM INSERTING into HOMEINSURANCE.LOCATION
SET DEFINE OFF;
Insert into HOMEINSURANCE.LOCATION (LOCATIONID,USERID,RESTYPE,ADDR1,ADDR2,CITY,STATENAME,ZIP,RESUSE) values (0,14,'test','test','test','test','test',0,'test');
REM INSERTING into HOMEINSURANCE.POLICY
SET DEFINE OFF;
REM INSERTING into HOMEINSURANCE.PROPERTY
SET DEFINE OFF;
REM INSERTING into HOMEINSURANCE.QUOTE
SET DEFINE OFF;
REM INSERTING into HOMEINSURANCE.USERLIST
SET DEFINE OFF;
Insert into HOMEINSURANCE.USERLIST (USERID,USERNAME,USERPASS,ROLE) values (14,'testUser','testPassword','ADMIN');
Insert into HOMEINSURANCE.USERLIST (USERID,USERNAME,USERPASS,ROLE) values (13,'John','john1234','ADMIN');
Insert into HOMEINSURANCE.USERLIST (USERID,USERNAME,USERPASS,ROLE) values (10,'bairon','bairon123','ADMIN');
--------------------------------------------------------
--  DDL for Index HOMEOWNER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOMEINSURANCE"."HOMEOWNER_PK" ON "HOMEINSURANCE"."HOMEOWNER" ("USERID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOMEINSURANCE"."UNIQUE_USER" ON "HOMEINSURANCE"."USERLIST" ("USERNAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table POLICY
--------------------------------------------------------

  ALTER TABLE "HOMEINSURANCE"."POLICY" MODIFY ("POLICYID" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."POLICY" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."POLICY" MODIFY ("QUOTEID" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."POLICY" MODIFY ("EFFECTIVEDATE" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."POLICY" MODIFY ("ENDDATE" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."POLICY" MODIFY ("TERM" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."POLICY" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."POLICY" ADD PRIMARY KEY ("POLICYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QUOTE
--------------------------------------------------------

  ALTER TABLE "HOMEINSURANCE"."QUOTE" MODIFY ("QUOTEID" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."QUOTE" MODIFY ("LOCATIONID" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."QUOTE" MODIFY ("MNTHLYPREMIUM" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."QUOTE" MODIFY ("DWELLINGCOVERAGE" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."QUOTE" MODIFY ("DETACHEDSTRUCTURE" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."QUOTE" MODIFY ("PERSONALPROPERTY" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."QUOTE" MODIFY ("ADDLLIVINGEXPENSE" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."QUOTE" MODIFY ("MEDICALEXPENSE" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."QUOTE" MODIFY ("DEDUCTIBLE" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."QUOTE" ADD PRIMARY KEY ("QUOTEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "HOMEINSURANCE"."LOCATION" MODIFY ("LOCATIONID" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."LOCATION" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."LOCATION" MODIFY ("RESTYPE" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."LOCATION" MODIFY ("ADDR1" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."LOCATION" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."LOCATION" MODIFY ("STATENAME" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."LOCATION" MODIFY ("ZIP" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."LOCATION" MODIFY ("RESUSE" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."LOCATION" ADD PRIMARY KEY ("LOCATIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERLIST
--------------------------------------------------------

  ALTER TABLE "HOMEINSURANCE"."USERLIST" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."USERLIST" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."USERLIST" MODIFY ("USERPASS" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."USERLIST" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HOMEINSURANCE"."USERLIST" ADD CONSTRAINT "UNIQUE_USER" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROPERTY
--------------------------------------------------------

  ALTER TABLE "HOMEINSURANCE"."PROPERTY" MODIFY ("LOCATIONID" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."PROPERTY" MODIFY ("MKTVAL" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."PROPERTY" MODIFY ("YR" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."PROPERTY" MODIFY ("SQFT" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."PROPERTY" MODIFY ("DWELLING" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."PROPERTY" MODIFY ("ROOFMTL" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."PROPERTY" MODIFY ("GARAGE" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."PROPERTY" MODIFY ("BATHS" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."PROPERTY" MODIFY ("HALFBATHS" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."PROPERTY" MODIFY ("POOL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOMEOWNER
--------------------------------------------------------

  ALTER TABLE "HOMEINSURANCE"."HOMEOWNER" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."HOMEOWNER" MODIFY ("FNAME" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."HOMEOWNER" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."HOMEOWNER" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."HOMEOWNER" MODIFY ("RETIRED" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."HOMEOWNER" MODIFY ("SSN" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."HOMEOWNER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HOMEINSURANCE"."HOMEOWNER" ADD CONSTRAINT "HOMEOWNER_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOMEOWNER
--------------------------------------------------------

  ALTER TABLE "HOMEINSURANCE"."HOMEOWNER" ADD CONSTRAINT "FK_USERID" FOREIGN KEY ("USERID")
	  REFERENCES "HOMEINSURANCE"."USERLIST" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "HOMEINSURANCE"."LOCATION" ADD CONSTRAINT "FK_USERID2" FOREIGN KEY ("USERID")
	  REFERENCES "HOMEINSURANCE"."USERLIST" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POLICY
--------------------------------------------------------

  ALTER TABLE "HOMEINSURANCE"."POLICY" ADD CONSTRAINT "USERID_FK3" FOREIGN KEY ("USERID")
	  REFERENCES "HOMEINSURANCE"."USERLIST" ("USERID") ENABLE;
  ALTER TABLE "HOMEINSURANCE"."POLICY" ADD CONSTRAINT "QUOTEID_FK" FOREIGN KEY ("QUOTEID")
	  REFERENCES "HOMEINSURANCE"."QUOTE" ("QUOTEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROPERTY
--------------------------------------------------------

  ALTER TABLE "HOMEINSURANCE"."PROPERTY" ADD CONSTRAINT "LOCATION_FK" FOREIGN KEY ("LOCATIONID")
	  REFERENCES "HOMEINSURANCE"."LOCATION" ("LOCATIONID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUOTE
--------------------------------------------------------

  ALTER TABLE "HOMEINSURANCE"."QUOTE" ADD CONSTRAINT "LOCATION_FK2" FOREIGN KEY ("LOCATIONID")
	  REFERENCES "HOMEINSURANCE"."LOCATION" ("LOCATIONID") ENABLE;
