package casestudy.homeinsurance.util;

public final class OracleSqlQueries {
	//for USERLIST
	public static final String SELECT_USER_BY_USERNAME = "SELECT * FROM USERLIST WHERE USERNAME = ?";
	public static final String REGISTER_USER = "INSERT INTO USERLIST (USERID, USERNAME, USERPASS) VALUES(?, ?, ?)";
	public static final String NUMBER_OF_USERS = "SELECT MAX(USERID) FROM USERLIST";
	public static final String SELECT_USER_BY_USERID = "SELECT * FROM USERLIST WHERE USERID = ?";
	//for HOMEOWNER
	public static final String SELECT_HOMEOWNER_BY_USERID = "SELECT * FROM HOMEOWNER WHERE USERID = ?";
	public static final String REGISTER_HOMEOWNER ="INSERT INTO HOMEOWNER (USERID, FNAME, LNAME, DOB, RETIRED, SSN, EMAIL) VALUES (?,?,?,?,?,?,?)";
	public static final String UPDATE_HOMEOWNER = "UPDATE HOMEOWNER SET FNAME = ?, LNAME = ?, DOB = ?, RETIRED = ?, SSN = ?, EMAIL = ? WHERE USERID = ?";
	public static final String CHECK_EXIST = "SELECT COUNT(USERID) FROM HOMEOWNER WHERE USERID = ?";
	//for LOCATION
	public static final String SELECT_LOCATION_BY_USERID = "SELECT * FROM LOCATION WHERE USERID = ?";
	public static final String REGISTER_LOCATION = "INSERT INTO LOCATION (LOCATIONID, USERID, RESTYPE, ADDR1, ADDR2, CITY, STATENAME, ZIP, RESUSE) VALUES (?,?,?,?,?,?,?,?,?)";
	public static final String NUMBER_OF_LOCATIONS = "SELECT MAX(LOCATIONID) FROM LOCATION";
	//for PROPERTY
	public static final String SELECT_PROPERTY_BY_LOCATIONID = "SELECT * FROM PROPERTY WHERE LOCATIONID = ?";
	public static final String REGISTER_PROPERTY = "INSERT INTO PROPERTY (LOCATIONID, MKTVAL, YR, SQFT, DWELLING, ROOFMTL, GARAGE, BATHS, HALFBATHS, POOL) VALUES (?,?,?,?,?,?,?,?,?,?)";
	public static final String UPDATE_PROPERTY = "UPDATE PROPERTY SET MKTVAL = ?, YR = ?, SQFT = ?, ROOFMTL = ?, GARAGE = ?, BATHS = ?, HALFBATHS = ?, POOL = ? WHERE LOCATIONID = ?";
	public static final String CHECK_PROP_EXIST = "SELECT * FROM PROPERTY WHERE LOCATIONID = ?";
	//for QUOTE
	public static final String SELECT_QUOTE_BY_PROPERTY_LOCATIONID = "SELECT * FROM QUOTE WHERE LOCATIONID = ?";
	public static final String REGISTER_QUOTE = "INSERT INTO QUOTE (QUOTEID, LOCATIONID, MNTHLYPREMIUM, DWELLINGCOVERAGE, DETACHEDSTRUCTURE, PERSONALPROPERTY, ADDLLIVINGEXPENSE, MEDICALEXPENSE, DEDUCTIBLE) VALUES (?,?,?,?,?,?,?,?,?)";
	public static final String NUMBER_OF_QUOTES = "SELECT MAX(QUOTEID) FROM QUOTE";
	public static final String RETRIEVE_QUOTES_FOR_USER = "SELECT QUOTE.* FROM QUOTE JOIN LOCATION ON LOCATION.LOCATIONID = QUOTE.LOCATIONID WHERE LOCATION.USERID = ?";
	
	//for POLICY
	public static final String SELECT_POLICY_BY_USERID = "SELECT * FROM POLICY WHERE USERID = ?";
	public static final String REGISTER_POLICY = "INSERT INTO POLICY ( POLICYID, USERID, QUOTEID, EFFECTIVEDATE, ENDDATE, TERM, STATUS) VALUES (?,?,?,?,?,?,?)";
	public static final String NUMBER_OF_POLICIES = "SELECT MAX(POLICYID) FROM POLICY";
	public static final String UPDATE_POLICY_STATUS = "UPDATE POLICY SET STATUS = ? WHERE POLICYID = ?";
	
	//Special delete for casestudy so selenium works right.
	public static final String SPECIAL_DELETE = "";
}